### PR TITLE
Dark theme support

### PR DESCRIPTION
**Pull request by NiklasRentzCAU**
Implements support for dark / other color themes for clients over the LSP and adds a property to be read by syntheses to conform to some theme-related foreground/background/highlighting colors.

Relates to kieler/KLighD#175

### CODE REVIEW

**Comment by NiklasRentzCAU** [comment]
Some yet-to-dos:

- [ ] let the CLI default light theme color be null to allow for an unaffected synthesis to render its default light theme colors and set own defaults
- [ ] automatically set the background to light/dark depending on the synthesis

**Comment by a-sr** [comment]
Regarding todo no. 2, I think there is also a preference in the klighd view that enforces a white background, in this case it woun't make much sense to activate/send color preferences for a dark theme, or do you mean this by no. 2?

**Comment by NiklasRentzCAU** [comment]
This PR might need to be closed and re-opened, GitHub falsely indicates most changes from the main branch to be part of this PR as well, although the branches differ only by a few changes.

**Comment by NiklasRentzCAU** [comment]
This PR shows 61 changed files, although there are only 9, closing and re-opening this one.

**Pull request closed without merging**
